<a href="https://colab.research.google.com/github/550tealeaves/DATA71200_sum2024_550/blob/main/Chap_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd

url = "https://raw.githubusercontent.com/amueller/mglearn/main/mglearn/data/adult.data"

col_names = ['age', 'workclass', 'fnlwgt', 'education', 'edu-num', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'capital-gain', 'cap-loss', 'hours-per-week', 'native-country', 'income']

adult_data = pd.read_csv(url, names = col_names)


#IPython.display gives nice formatting to Jupyter notebooks
adult_data.head() #displays all the columns

,age,workclass,fnlwgt,education,edu-num,marital-status,occupation,relationship,race,gender,capital-gain,cap-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [30]:
#Select some cols
data = adult_data[['age', 'workclass', 'education', 'gender', 'hours-per-week', 'occupation', 'income']]

display(data.head())

,age,workclass,education,gender,hours-per-week,occupation,income
0,39,State-gov,Bachelors,Male,40,Adm-clerical,<=50K
1,50,Self-emp-not-inc,Bachelors,Male,13,Exec-managerial,<=50K
2,38,Private,HS-grad,Male,40,Handlers-cleaners,<=50K
3,53,Private,11th,Male,40,Handlers-cleaners,<=50K
4,28,Private,Bachelors,Female,40,Prof-specialty,<=50K

In [28]:
#value_counts method checks col contents
print(data.gender.value_counts()) #will show male 21790, female 10771

gender
 Male      21790
 Female    10771
Name: count, dtype: int64

In [ ]:
print("Original features: \n", list(data.columns), " \n")
data_dummies = pd.get_dummies(data)
print("Features after get_dummies: \n", list(data_dummies.columns))

In [ ]:
#display 1st 5 rows
data_dummies.head()

In [ ]:
features = data_dummies.loc[:, 'age':'occupation_ Transport-moving']
#Extract NumPy arrays
x = features.values
y = data_dummies['income_ >50K'].values
print("x.shape: {} y.shape: {}".format(x.shape, y.shape))